name: Metrics
on:
  schedule: 
    - cron: "0 * * * *" 
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  generate_metrics:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
